# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-17 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0002_auto_20190317_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cutomers', models.ManyToManyField(to='mymodel.Person')),
            ],
        ),
    ]
