# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-17 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0003_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='cutomers',
            new_name='customers',
        ),
    ]
