# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0006_delete_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('milik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.Person')),
            ],
        ),
    ]
