# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0007_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='milik',
            new_name='belongs_to',
        ),
    ]
