# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0010_auto_20190403_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ox',
            options={'ordering': ['horn_length']},
        ),
    ]
