# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0012_auto_20190403_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='mymodel_base1_related', related_query_name='mymodel_base1s', to='mymodel.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
