# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0014_auto_20190403_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base1',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mymodel.Base')),
                ('city', models.CharField(max_length=100)),
            ],
            bases=('mymodel.base',),
        ),
    ]
