# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0015_base1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildB',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mymodel.Base')),
                ('city', models.CharField(max_length=100)),
            ],
            bases=('mymodel.base',),
        ),
        migrations.RenameModel(
            old_name='Base1',
            new_name='ChildA',
        ),
        migrations.RenameField(
            model_name='childa',
            old_name='city',
            new_name='name',
        ),
    ]
