# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0018_childa_childb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childa',
            name='members',
        ),
        migrations.RemoveField(
            model_name='childb',
            name='members',
        ),
        migrations.DeleteModel(
            name='ChildA',
        ),
        migrations.DeleteModel(
            name='ChildB',
        ),
    ]
