# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel2', '0013_auto_20190410_0707'),
        ('mymodel', '0022_childa_childb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childa',
            name='members',
        ),
        migrations.RemoveField(
            model_name='childb',
            name='members',
        ),
        migrations.DeleteModel(
            name='ChildA',
        ),
        migrations.DeleteModel(
            name='ChildB',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
