# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0023_auto_20190410_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ancestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChildA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ancestor', models.ManyToManyField(related_name='mymodel_childa_related', related_query_name='mymodel_childas', to='mymodel.Ancestor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('ancestor', models.ManyToManyField(related_name='mymodel_childb_related', related_query_name='mymodel_childbs', to='mymodel.Ancestor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
