# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0035_place_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='place_ptr',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
