# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0037_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mymodel.place',),
        ),
    ]
