# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0038_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base1',
            fields=[
                ('base1_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Base2',
            fields=[
                ('base2_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyObj',
            fields=[
                ('base2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='mymodel.Base2')),
                ('base1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mymodel.Base1')),
            ],
            bases=('mymodel.base1', 'mymodel.base2'),
        ),
    ]
