# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0043_auto_20190415_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='n_comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='n_pingbacks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
