# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0044_auto_20190415_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymodel.Blog'),
        ),
    ]
