# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0045_auto_20190417_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tagline',
            field=models.TextField(null=True),
        ),
    ]
