# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0048_entrydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydetail',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='mymodel.Entry'),
        ),
    ]
