# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0049_auto_20190423_1933'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='entry',
        #    name='authors',
        #),
        #migrations.RemoveField(
        #    model_name='entry',
        #    name='blog',
        #),
        #migrations.RemoveField(
        #    model_name='entrydetail',
        #    name='entry',
        #),
        #migrations.DeleteModel(
        #    name='Author',
        #),
        #migrations.DeleteModel(
        #    name='Entry',
        #),
        #migrations.DeleteModel(
        #    name='EntryDetail',
        #),
    ]
