# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0050_auto_20190424_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('pages', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('pub_date', models.DateField()),
                ('authors', models.ManyToManyField(to='mymodel.Author')),
            ],
        ),
        #migrations.CreateModel(
        #    name='Entry',
        #    fields=[
        #        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #        ('headline', models.CharField(max_length=255)),
        #        ('body_text', models.TextField()),
        #        ('pub_date', models.DateField(blank=True, null=True)),
        #        ('mod_date', models.DateField(blank=True, null=True)),
        #        ('n_comments', models.PositiveIntegerField(default=0)),
        #        ('n_pingbacks', models.PositiveIntegerField(default=0)),
        #        ('rating', models.PositiveIntegerField(default=0)),
        #        ('authors', models.ManyToManyField(to='mymodel.Author')),
        #        ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymodel.Blog')),
        #    ],
        #),
        #migrations.CreateModel(
        #    name='EntryDetail',
        #    fields=[
        #        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #        ('details', models.TextField()),
        #        ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='mymodel.Entry')),
        #    ],
        #),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_awards', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registered_user', models.PositiveIntegerField()),
                ('books', models.ManyToManyField(to='mymodel.Book')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymodel.Publisher'),
        ),
    ]
