# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0054_auto_20190425_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelManagers(
            name='publisher',
            managers=[
                ('appear', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='hometown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mymodel.City'),
        ),
    ]
