# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0055_auto_20190506_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='hometown',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
