# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0057_auto_20190506_1153'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publisher',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='publisher',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mymodel.City'),
        ),
    ]
