# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 18:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0058_auto_20190506_2241'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
    ]
