# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import mymodel.models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0059_auto_20190527_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(validators=[mymodel.models.age_validator])),
            ],
        ),
    ]
