# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mymodel', '0013_base1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base2',
            fields=[
                ('base1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mymodel.Base1')),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('mymodel.base1',),
        ),
    ]
