# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mymodel', '0013_base1'),
        ('mymodel2', '0002_auto_20190403_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('members', models.ManyToManyField(related_name='mymodel2_base2_related', related_query_name='mymodel2_base2s', to='mymodel.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
