# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mymodel', '0015_base1'),
        ('mymodel2', '0004_auto_20190403_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base2',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mymodel.Base')),
                ('age', models.PositiveIntegerField()),
            ],
            bases=('mymodel.base',),
        ),
    ]
