# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mymodel', '0026_ancestor_childa_childb'),
        ('mymodel2', '0015_auto_20190410_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('ancestors', models.ManyToManyField(related_name='mymodel2_childb_related', related_query_name='mymodel2_childbs', to='mymodel.Ancestor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
