# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 02:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import modelform_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField(default=datetime.date(2019, 5, 30), editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, validators=[modelform_app.models.title_validator]),
        ),
    ]
