# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-30 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelform_app', '0002_auto_20190530_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 30, 2, 25, 50, 454137, tzinfo=utc), editable=False),
        ),
    ]
