# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelform_app', '0003_auto_20190530_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text='Use puns liberally', max_length=200, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='journal',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 31, 2, 4, 9, 896779, tzinfo=utc), editable=False),
        ),
    ]
