# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelform_app', '0004_auto_20190531_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 31, 9, 37, 41, 201662, tzinfo=utc), editable=False),
        ),
    ]
