# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelform_app', '0005_auto_20190531_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 5, 15, 48, 1, 605658, tzinfo=utc), editable=False),
        ),
    ]
