# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modelform_app', '0008_auto_20190605_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 20, 7, 24, 2, 660682, tzinfo=utc), editable=False),
        ),
    ]
